# Generated by Django 2.2.1 on 2019-05-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('area_parent', models.ForeignKey(blank=True, null=True, on_delete=True, to='book.AreaInfo')),
            ],
        ),
    ]
